#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import sys
import subprocess

request = json.load(sys.stdin)
group = request['group']

altergroup_cmd = ['podman', 'exec', 'openldap', 'alter-group']

if 'users' in request:
    altergroup_cmd += ['-u', ','.join(request['users'])]

if 'description' in request:
    altergroup_cmd += ['-d', request['description']]

altergroup_cmd.append(group)

subprocess.run(altergroup_cmd, stdout=sys.stderr, check=True, text=True)

json.dump({"status": "success", "message": "group_altered"}, fp=sys.stdout)
