#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import sys
import subprocess

request = json.load(sys.stdin)
user = request['user']

alteruser_cmd = ['podman', 'exec', '-i', 'openldap', 'alter-user']

if 'password' in request:
    alteruser_cmd += ['-p', '-']  # write password to helper's stdin

if 'groups' in request:
    alteruser_cmd += ['-g', ','.join(request['groups'])]

if 'display_name' in request:
    alteruser_cmd += ['-d', request['display_name']]

if 'locked' in request:
    if request['locked'] == True:
        alteruser_cmd += ['-l']
    else:
        alteruser_cmd += ['-u']

alteruser_cmd.append(user)

subprocess.run(alteruser_cmd, input=request.get('password'),
               stdout=sys.stderr, check=True, text=True)

json.dump({"status": "success", "message": "user_altered"}, fp=sys.stdout)
